language: cpp
sudo: true
dist: trusty

compiler:
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y cppcheck libboost-dev libboost-all-dev libcurl4-gnutls-dev liblog4cplus-dev libmicrohttpd-dev libsqlite3-dev heirloom-mailx libxml-simple-perl cppcheck rats; fi

script:
  - EXTFLAGS="" make all
  - ./analyzeSource.pl 2>report.html
  - echo "Report attachment" | mail -a report.html -s "Report $TRAVIS_JOB_NUMBER" $JOB_MAIL_TO

branches:
  only:
    - master
    - /^issue\d+/
    - /^v\d+\./

notifications:
  email:
    on_success: always
    on_failure: always

env:
  global:
    - LANG="en_US.UTF-8"

os:
  - linux
